---
title: "R Notebook"
output: 
  github_document:
    toc: true
    toc_detph: 2
---

```{bash}
sudo apt-get install -y liblzma-dev libbz2-dev
```

##Les Packages que nous aurons besoin

```{r}
.cran_packages <- c( "shiny","miniUI", "caret", "pls", "e1071", "ggplot2", "randomForest", "dplyr", "ggrepel", "nlme", "devtools",
                  "reshape2", "PMA", "structSSI", "ade4",
                  "ggnetwork", "intergraph", "scales")
.github_packages <- c("jfukuyama/phyloseqGraphTest")
.bioc_packages <- c("genefilter", "impute")
# Install CRAN packages (if not already installed)
.inst <- .cran_packages %in% installed.packages()
if (any(!.inst)){
  install.packages(.cran_packages[!.inst],repos = "http://cran.rstudio.com/")
}
.inst <- .github_packages %in% installed.packages()
if (any(!.inst)){
  devtools::install_github(.github_packages[!.inst])
}
.inst <- .bioc_packages %in% installed.packages()
if(any(!.inst)){
  source("http://bioconductor.org/biocLite.R")
  biocLite(.bioc_packages[!.inst])
}
```
```{r}
library("knitr")
BiocManager::install("BiocStyle")
library("BiocStyle")
```


```{r}
library("dada2")
```

```{r}
BiocManager::install("phangorn")
BiocManager::install("DECIPHER")
```
```{r}
library(phangorn)
library(DECIPHER)
```

##Pour les graphiques regroupés
```{r}
install.packages("gridExtra")
```
```{r}
library(gridExtra)
```

## Hiérarchiser les tests multiples
```{r package install}
BiocManager::install("DESeq2")
```

```{r}
library(DESeq2)
```

```{bash}
wget https://cran.r-project.org/src/contrib/Archive/structSSI/structSSI_1.1.1.tar.gz
```

```{r package install}
library(devtools)
install_local("./structSSI_1.1.1.tar.gz")
```